import path from 'node:path';
import { chromium } from 'playwright-core';
import { startMockServer } from './mock-api.mjs';
const here = path.dirname(new URL(import.meta.url).pathname);
const dist = path.join(here, '..', 'dist'), tmp = path.join(here, '.tmp');
const experience = { id: '64b000000000000000000001', payload: (base) => ({ id: '64b000000000000000000001', cardId: { title: 'Test' }, tracking: { status: 'ready', url: `${base}/uploads/front.mind`, targets: [{ face: 'front', width: 669, height: 1000 }] }, arTemplateData: { mainHeading: 'Hi', paragraph1: 'There', effect: 'hearts' }, templateImage0: `${base}/uploads/front.png`, templateVideo: `${base}/uploads/video.webm` }) };
const { server, port } = await startMockServer({ distDir: dist, tmpDir: tmp, experience });
const base = `http://127.0.0.1:${port}`;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream', `--use-file-for-fake-video-capture=${path.join(tmp, 'cam.y4m')}`, '--autoplay-policy=no-user-gesture-required', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader', '--use-gl=angle', '--use-angle=swiftshader', '--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, permissions: ['camera'] });
const page = await ctx.newPage();
page.on('console', (m) => console.log('[console]', m.type(), m.text().slice(0, 200)));
const r = await page.request.get(`${base}/uploads/video.webm`); console.log('video.webm fetch:', r.status(), r.headers()['content-type'], (await r.body()).length);
await page.goto(`${base}/?templateId=${experience.id}&api=${encodeURIComponent(base)}`);
await page.click('#btn-start');
await page.waitForFunction(() => window.__incardible.found === true, null, { timeout: 60000 });
await page.waitForTimeout(3000);
const info = await page.evaluate(() => {
  const s = window.__incardible; const c = s.content[0]; const v = c.video;
  const kids = []; c.group.traverse((o) => { if (o !== c.group) kids.push(`${o.type}${o.visible ? '' : '(hidden)'}${o.geometry ? ':' + o.geometry.type : ''}`); });
  const canPlay = { webm: v.canPlayType('video/webm; codecs="vp8"'), mp4: v.canPlayType('video/mp4; codecs="avc1.42E01E"') };
  return { playError: c.group.userData.playError, video: { src: v.currentSrc, readyState: v.readyState, networkState: v.networkState, paused: v.paused, error: v.error && v.error.code, muted: v.muted, w: v.videoWidth, h: v.videoHeight, t: v.currentTime }, canPlay, kids, triangles: s.triangles };
});
console.log(JSON.stringify(info, null, 1));
await browser.close(); server.close();
